#!/bin/bash
#
# Generated by Drun v3.5.0
# Case: Unknown
# Step: 1/1 - Generate Fake Data
# Generated at: 2025-11-27 00:35:48
#

set -e  # Exit on error

echo "=== Step 1: Generate Fake Data ==="

curl 'https://postman-echo.com/post' \
  --data-raw '{"user_name":"${fake_name()}","user_email":"${fake_email()}","user_address":"${fake_address()}","short_bio":"${fake_text(20)}","ip":"${fake_ipv4()}","company":"${fake_company()}"}'

echo ""
echo "✅ Request completed"